### ISSUE TITLE
Create a automatic update process

### ISSUE THREAD

**Issue by alexander-schranz** [alexander-schranz/symfony-recipes-yaml-to-php-converter#2]
The repositories need some script which update the current php recipes and regenerate all package from stretch:

Something like

```bash
vendor/bin/yaml-to-php git@github.com:symfony/recipes.git

# later in the github CI it should push it
git add .
git commit 
git push
```

# TODO

 - [x] Move clone and update of yaml to php file into a converter (is now this repository)
 - [x] Create Github action to call the script
 - [x] Push changes to main branch of repositories

**Comment by alexander-schranz** [comment]
Inspiration if we go with a PR based Bot so we can check if the config transformer work like expected can be found here: https://github.com/async-aws/aws/blob/4d1026ef70de5996d8056c88151d6a1036c3b124/.github/workflows/watch.yml#L54-L67 maybe @Nyholm can give us information how to setup a bot like this for the two repositories.

**Comment by alexander-schranz** [comment]
The automatic update process is implemented currently we will go still over a review process to make sure we check the changes, but the bot will create the PR.
